# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [23]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [47]:
A = np.arange(1, 16).reshape(3,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
print(A.ndim)
print(A.shape)
print(A.itemsize)
print(A.nbytes)
print(A.dtype)



2
(3, 5)
8
120
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [223]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


* Elementwise subtraction.

In [221]:
B-C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

* Elementwise multiplication.

In [222]:
B*C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

* Matrix multiplication (by default you should use the @ operator).

In [73]:

#D=np.matmul(B,C)
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

In [18]:
print(C.dtype)
print(C.shape)


float64
(3, 3)


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [45]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [224]:
H = np.exp(B)
H

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [29]:
print(B.max()) #calculating max value in whole matrix


9


In [31]:
print(B.min(axis=1)) #calculating min value in each row

[1 4 7]


In [32]:
print(B.min(axis=0)) #calculating min value in each column

[1 2 3]


In [34]:
print(B.sum()) #calculating sum value of the whole matrix

45


In [36]:
print(B.mean(axis=0)) #calculating mean value in each column

[4. 5. 6.]


In [46]:
M=np.median(B,axis=0) #calculating median value in each column
print(M)

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [48]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [49]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

If you only specify one index, when slicing,for a two dementionel matrix (matrix[row, column])  for example, it will select that row you specified and  include all elements along the other axis

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [50]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [51]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [52]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [53]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Line 1 generates a NumPy array that starts at 0 and creates sequential numbers up to 29. It is then reshaped into a 3-dimensional array with a depth of 2 (axis 0 contains 2 subarrays).

Here, axis 1=3 specifies the number of rows for each grouping, and -1 indicates that axis 2 will be automatically adjusted based on the other dimensions. In this case, it results in 5 columns.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [231]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [232]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [233]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [66]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [236]:
import numpy as np

def add_mult_matrices(P, O, operation):
    # 1. Validate that inputs are numpy.ndarray
    if not isinstance(P, np.ndarray) or not isinstance(O, np.ndarray):
           print("Both inputs must be of type numpy.ndarray.")
    
    # 2. Validate the operation type
    if operation not in ["add", "multiply"]:
           print("The operation must be either 'add' or 'multiply'.")

    if operation == "add":
        # 3. Check if matrices are of the same size for addition
        if P.shape != O.shape:
            print("For addition, matrices must have the same dimensions.")
        return P + O

    elif operation == "multiply":
        # 4. Check if matrices conform for multiplication
        if P.shape[1] != O.shape[0]:
            print("For multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix.")
        return P @ O # '@' operator performs matrix multiplication in numpy
    
R=add_mult_matrices(B, C, "add")
print(R)




[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

Assigment 10.1.1

a)

In [187]:
x = np.array([4, 3])
#x.shape
x.ndim

1

b)

In [162]:
5*x



array([20, 15])

c)

In [163]:
3*x

array([12,  9])

d)

In [164]:
5*x + 3*x

array([32, 24])

e)

In [165]:
8*x

array([32, 24])

f)

In [166]:
4*x-x

array([12,  9])

g)

In [207]:
c=x.reshape(-1,1)
#c, c.shape, 
c.ndim, c



(2,
 array([[4],
        [3]]))

h)Operation  x+x^T is not defined. Objekts do not have the same demensions

i)

In [195]:
m=np.linalg.norm(c)
print(m)

5.0


Assigment 10.1.2

In [188]:
y = np.array([3,7,0,11])
d = y.reshape(-1,1)
d

array([[ 3],
       [ 7],
       [ 0],
       [11]])

a)

In [238]:
d.ndim, d.shape

(2, (4, 1))

In [192]:
2*d

array([[ 6],
       [14],
       [ 0],
       [22]])

In [193]:
5*d+ 2*d

array([[21],
       [49],
       [ 0],
       [77]])

In [196]:
4*d- 2*d

array([[ 6],
       [14],
       [ 0],
       [22]])

In [220]:
f=d.reshape(-1)
f.ndim
print(f)
print(f.ndim)

[ 3  7  0 11]
1


In [205]:
n=round(np.linalg.norm(f),2)
print(n)

13.38


Assigment 10.1.3

In [212]:
v_1 = np.array([4, 3, 1, 5])
v_2 = np.array([2, 3, 1, 1])

a)

In [215]:
s=round(np.linalg.norm(v_1),2)
print(s)

7.14


b)

In [218]:
distance=round(np.linalg.norm(v_1-v_2), 2)
print(distance)

4.47


In [77]:
R=add_mult_matrices(B, C, "add")
print(R)

[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [81]:
A_1 = np.array([[2, 1, -1], [1, -1, 1]])
B_1 =np.array([[4,-2,1], [2,-4,-2]])
print(A_1)
print(B_1)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]


Exercise 10.2.1

a)

In [145]:
2*A_1


array([[ 4,  2, -2],
       [ 2, -2,  2]])

b)

In [146]:
B_1 - 2*A_1 #Matrices have the same shape so substruction is defined

array([[ 0, -4,  3],
       [ 0, -2, -4]])

c) Operation is not defined. Matrixes have different shape

In [143]:
C_1 = np.array([[1, 2], [2, 1]])
E_1 = np.array([[1, 2]])
C_1, E_1

(array([[1, 2],
        [2, 1]]),
 array([[1, 2]]))

In [142]:
C_1.shape, E_1.shape

((2, 2), (1, 2))

d)

In [144]:
D_1 = np.array([[3, 4], [4, 3]])
print(D_1)

[[3 4]
 [4 3]]


In [94]:
2*D_1 - 3*C_1 #Matrices have the same shape so substruction is defined

array([[3, 2],
       [2, 3]])

e)

In [95]:
D_1.T + 2*D_1 #Matrices have the same shape so addition is defined

array([[ 9, 12],
       [12,  9]])

In [131]:
R=add_mult_matrices(D_1.T, 2*D_1, "add")
print(R)

[[ 9 12]
 [12  9]]


f)

In [98]:
2*C_1.T - 2*D_1.T 

array([[-4, -4],
       [-4, -4]])

g)Operation in not defined. Matrices have different shape

h) A_1 @ C_1 Operation is not defined. Amount columns in matrix A_1 is not equel amount rows in matrix C_1

In [101]:
A_1.shape, C_1.shape

((2, 3), (2, 2))

In [132]:
R=add_mult_matrices(A_1, C_1, "multiply")
print(R)

For multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix.


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

i)

In [102]:
C_1 @ D_1

array([[11, 10],
       [10, 11]])

In [116]:
R=add_mult_matrices(C_1, D_1, "multiply")
print(R)

[[11 10]
 [10 11]]


j) C_1 @ B_1 Operation is defined. Amount columns in matrix C_1 is equel amount rows in matrix B_1

In [103]:
C_1.shape, B_1.shape

((2, 2), (2, 3))

In [104]:
C_1 @ B_1

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

In [133]:
R=add_mult_matrices(C_1, B_1, "multiply")
print(R)

[[  8 -10  -3]
 [ 10  -8   0]]


k)

In [106]:
I_1 = np.array([[1, 0], [0, 1]])
print(I_1)

[[1 0]
 [0 1]]


In [110]:
C_1.shape, I_1.shape, C_1 @ I_1

((2, 2),
 (2, 2),
 array([[1, 2],
        [2, 1]]))

In [134]:
R=add_mult_matrices(C_1, I_1, "multiply")
print(R)

[[1 2]
 [2 1]]


l) A_1 @ B_1.T  Operation is  defined. Amount columns in matrix A_1 is  equel amount rows in matrix B_1.T


In [113]:
A_1.shape, B_1.T.shape

((2, 3), (3, 2))

In [114]:
A_1 @ B_1.T

array([[5, 2],
       [7, 4]])

In [136]:
R=add_mult_matrices(A_1, B_1.T, "multiply")
print(R)

[[5 2]
 [7 4]]


Assigment 10.2.2

In [147]:
A_2 = np.array([[2, 3, 4], [5, 4, 1]])
A_2

array([[2, 3, 4],
       [5, 4, 1]])

In [150]:
A_2.shape, A_2.T.shape, A_2 @ A_2.T

((2, 3),
 (3, 2),
 array([[29, 26],
        [26, 42]]))

In [151]:
R=add_mult_matrices(A_2, A_2.T, "multiply")
print(R)

[[29 26]
 [26 42]]


Assigment 10.2.2

In [152]:
A_3 = np.array([[1, 2], [2, 4]])
B_3 = np.array([[2, 1], [1, 3]]) 
C_3 = np.array([[4, 3], [0, 2]])                          
A_3, B_3, C_3

(array([[1, 2],
        [2, 4]]),
 array([[2, 1],
        [1, 3]]),
 array([[4, 3],
        [0, 2]]))

In [154]:
(A_3 @ B_3) == (A_3 @ C_3)

array([[ True,  True],
       [ True,  True]])

In [155]:
B_3 == C_3

array([[False, False],
       [False, False]])

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [137]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [138]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [139]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
